spring:
  application:
    name: vlad-data-receiver
  datasource:
    url: jdbc:mysql://localhost:3306/vlad_db
    username: root
    password: ${DB_PASSWORD}
  cache:
    type: caffeine
    cache-names:
      - unloadingCache
      - operationalDayCache
    caffeine:
      spec: expireAfterWrite=60s,maximumSize=1000

app:
  storage:
    base-path: ./storage/documents
    archive-format: .zip
    date-format: yyyyMMdd

logging:
  level:
    ru.vlad: DEBUG
    org.springframework.jdbc: DEBUG
  charset:
    console: UTF-8

insert-operdays-scheduler: 0 0 7 27 * ?